## In this lesson, we explored the following NumPy topics:

1. **dtype**: Determines the data type of an array’s elements.
2. **astype()**: Converts an array from one data type to another.
3. **Slicing**: Extracts specific portions of an array in one or more dimensions.
4. **reshape()**: Changes the shape of an array without modifying its data.
5. **flatten()**: Converts an array into a one-dimensional copy.
6. **concatenate()**: Combines multiple arrays into one.
7. **Masking**: Selects elements from an array using a Boolean condition.
8. **Random arrays**: Creates arrays with randomly generated values.


In [1]:
import numpy as np

# dtype

In [2]:
a=np.array([2,0,-5])
print(f"The dimension of 'a' is: {a.ndim}")            # show Dimention
b=np.array([2,3,5],ndmin=2)     # convert to 2D
print(f"The dimension of 'b' is: {b.ndim}")            # show Dimention

The dimension of 'a' is: 1
The dimension of 'b' is: 2


In [3]:
b  #two Brackets in output of this line influence that our array have 2 dimension

array([[2, 3, 5]])

In [4]:
print(f"The type of 'a' array is: {a.dtype}")
print(f"The type of 'b' array is: {b.dtype}")

The type of 'a' array is: int32
The type of 'b' array is: int32


# astype()

In [5]:
print(f'convert the int type of this array to float type by astype format --> b: {b.astype("float")}')

convert the int type of this array to float type by astype format --> b: [[2. 3. 5.]]


In [6]:
a.astype('complex')

array([ 2.+0.j,  0.+0.j, -5.+0.j])

In [7]:
a.astype('str')

array(['2', '0', '-5'], dtype='<U11')

In [8]:
a.astype('bool')   # every numbers except 0 in bool type are True forexample in a=np.array([2,0,-5]) 

array([ True, False,  True])

# Slicing

**Slicing 1-D Arrays(vector)**

In [9]:
c=np.array([2,3,4,5,6,7])
c[2:4]    # Slicing in python means taking elements from one given index to another given index.

array([4, 5])

In [10]:
c[:]      # whitout slicing 

array([2, 3, 4, 5, 6, 7])

In [11]:
c[::]     # whitout slicing and the numbers of step!

array([2, 3, 4, 5, 6, 7])

**Negative Slicing :** Slice from the index 3 from the end to index 1 from the end

In [12]:
print(c[-3:-1])    # -1 is the end of number in array

[5 6]


**STEP :** Use the step value to determine the step of the slicing

In [14]:
print(c[1:5:2])   # number of step is 2

[3 5]


**Slicing 2-D Arrays(matrix)**

In [41]:
d=np.array([[300,400,500,600],[3,4,5,6]])
print(f"The shape of d array is : {d.shape} index 0 is about the number of rows and another one (index 1) is the number columns ")
print(d)

The shape of d array is : (2, 4) index 0 is about the number of rows and another one (index 1) is the number columns 
[[300 400 500 600]
 [  3   4   5   6]]


In [42]:
print('1',d[:])     # Select all elements from start to end
print('2',d[:, 1])  # Slicing: Get all rows from the second column (index 1)
print('3',d[1, :])  # Slicing: Get the second row (index 1) and all its columns

1 [[300 400 500 600]
 [  3   4   5   6]]
2 [400   4]
3 [3 4 5 6]


In [43]:
print(d[0,:])      # Slicing: Get the first row (index 0) and all its columns

[300 400 500 600]


In [45]:
print(d[0:2, 2])   # Select rows 0 and 1, and only the column at index 2

[500   5]


# reshape()

**Requirement for reshape()**: The product of the new dimensions must equal the total number of elements in the original array.

For an array with shape (2, 4), the product is 8. Valid reshapes include (8, 1), (4, 2), or (2, 2, 2).



**Old Shape Total Elements=New Shape Total Elements**

In [48]:
a.reshape(3,1)   # 1x3 = 3x1 

array([[ 2],
       [ 0],
       [-5]])

In [62]:
#d.shape was (2,4)  
print('1',d.reshape(4,2))
print('2',d.reshape(1,8))
print('3',d.reshape(8,1))
print('4',d.reshape(2,2,2))

1 [[300 400]
 [500 600]
 [  3   4]
 [  5   6]]
2 [[300 400 500 600   3   4   5   6]]
3 [[300]
 [400]
 [500]
 [600]
 [  3]
 [  4]
 [  5]
 [  6]]
4 [[[300 400]
  [500 600]]

 [[  3   4]
  [  5   6]]]


**reshape(-1)** : Flatten the array into a 1D array

In [69]:
print(d.reshape(-1))    
print(a.reshape(-1))
print(b.reshape(-1))

[300 400 500 600   3   4   5   6]
[ 2  0 -5]
[2 3 5]


# flatten()

In [66]:
print(a.flatten())
print(a.ravel())
print(a.reshape(-1))

[ 2  0 -5]
[ 2  0 -5]
[ 2  0 -5]


# concatenate()

In [80]:
d=np.array([[300,400,500,600],[3,4,5,6]])   #shape = (2,4)
e=np.array([[-1,0,1,2],[23,99,64,39]])      #shape = (2,4)
f=np.concatenate((d,e),axis=1)
print(f.shape)
f

(2, 8)


array([[300, 400, 500, 600,  -1,   0,   1,   2],
       [  3,   4,   5,   6,  23,  99,  64,  39]])

In [92]:
g=np.array_split(a,3)    #1-D   split
print(g)
g

[array([2]), array([0]), array([-5])]


[array([2]), array([0]), array([-5])]

In [91]:
g=np.array_split(d,8)    #2-D   split
print(g)
g

[array([[300, 400, 500, 600]]), array([[3, 4, 5, 6]]), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32)]


[array([[300, 400, 500, 600]]),
 array([[3, 4, 5, 6]]),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32),
 array([], shape=(0, 4), dtype=int32)]

# Masking

# Random arrays